### ISSUE TITLE
[subscribe] don't use host.docker.internal

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#181]
tl;dr: `host.docker.internal` is only supported on Mac, not on Linux.

```
> omg subscribe listen heartbeat -a eventName='heartbeat'
✔ Built Docker image with name: omg/microservices/node
✔ Started Docker container: ee75ac9a990a
✔ Health check passed
✔ Ran action: `listen` with output: 
✔ Subscribed to event: `heartbeat` data will be posted to this terminal window when appropriate
...

> docker logs ee75ac9a990a
Listening on localhost:8080
[subscribe] id:'00120a0c-f7f2-4fd4-8546-4203f3163690', endpoint:'http://host.docker.internal:5459', name:'heartbeat'
[publish] 'heartbeat' payload:  { time:
   'Sat Apr 06 2019 18:03:00 GMT+0000 (Coordinated Universal Time)' }
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND host.docker.internal host.docker.internal:5459
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at Request.onRequestError (/app/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This is a well-known Docker issue: https://github.com/docker/for-linux/issues/264
There seems to be some movement in this gigantic issue, so I presume this will get fix soonish, but in either way it will take year to propagate to the individual Linux distributions, so the CLI should detect its exposed hostIP and use that one.

For now, this is my ugly workaround:

```js
const cp = require('child_process');

var hostIP = "";
cp.exec("ip -4 route list match 0/0", (e, stdout, stderr) => {
  hostIP = stdout.split(" ")[2];
});

function normalize(url) {
  return url.replace("host.docker.internal", hostIP);
}
```

**Comment by wilzbach** [comment]
This regressed in 0.16.1:

```
$ oms subscribe --debug event triggered -a name=delay
✔ Built Docker image with name: oms/l2hvbwuvc2vil2fzew5jes9vbxmtc2nozwr1bgu
✔ Successfully started Docker container
ℹ Listening on localhost:8080
✔ Healthcheck successful
ℹ [subscribe] id:'bc63f386-02c3-4b50-9dbf-03f527e33a6d', endpoint:'http://host.docker.internal:41011', name:'triggered', payload:  { name: 'delay' }
```

**Comment by StoryscriptHuman** [comment]
https://github.com/microservices/oms/issues/181
